#! /bin/bash
#
# mpihello.job
#
#$ -j y
#$ -o $HOME/mpihello.out
#
#$ -N MPIHELLOCLUSTER # job name
#
#$ -pe dev 2
#$ -l res_cpus=8
#$ -l res_mem=4000
#$ -l res_tmpfs=1000
#
#$ -l res_image=nrc_all_default_ubuntu-14.04-amd64_latest
##$ -l res_image=nrcan_all_default_ubuntu-14.04-amd64_latest
#
#$ -l h_rt=600

# load mpi environment
. ssmuse-sh -x hpco/exp/openmpi-1.6.5

# call your program
rumpirun ~/github/hpc/mpihello 10 2
